from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user),
    path('register/', views.register_user),
    path('logout/', views.logout_user,name="logout"),
    path('admin-dashboard/', views.admin_dashboard, name='admin'),
    path('client-dashboard/', views.client_dashboard, name='client'),
    path('send-otp/', views.send_otp),
    path('verify-otp/', views.verify_otp),
    path('reset-password-otp/', views.reset_password_otp),
    path('staff-dashboard/', views.staff_dashboard),
    path('chat/', views.chat_api),
    path('chatbot/', views.chatbot_page),
    path('add-citizen/', views.add_citizen),
    path('get-citizens/', views.get_citizens),
    path('delete-citizen/<int:id>/', views.delete_citizen),
    path('add-doctor/', views.add_doctor),
    path('get-doctors/', views.get_doctors),
    path('delete-doctor/<int:id>/', views.delete_doctor),
    path('add-timing/', views.add_timing),
    path('get-timings/', views.get_timings),
    path('add-appointment/', views.add_appointment),
    path('get-appointments/', views.get_appointments),
    path('delete-timing/<int:id>/', views.delete_timing),
    path("save-opd-bill/", views.save_opd_bill, name="save_opd_bill"),
    path("get-serial/", views.get_serial),
    path("get-opd-bills/", views.get_opd_bills),
    path("delete-opd-bill/<int:id>/", views.delete_opd_bill),
    path("update-opd-bill/<int:id>/", views.update_opd_bill),
    path("get-staff/", views.get_staff),
    path("get-drivers/", views.get_drivers),
    path("get-pending-requests/", views.get_pending_requests),

    path("approve-staff/<int:id>/", views.approve_staff),
    path("reject-staff/<int:id>/", views.reject_staff),
    path('get-today-opd-bills/', views.get_today_opd_bills),
    path("approve-driver/<int:id>/", views.approve_driver),
    path("reject-driver/<int:id>/", views.reject_driver),
    path("dashboard-data/", views.get_dashboard_data),
]