# Generated by Django 6.0 on 2026-04-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_type', models.CharField(choices=[('REGULAR', 'Regular'), ('CUSTOM', 'Custom')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('booking_start', models.DateTimeField(blank=True, null=True)),
                ('booking_end', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
    ]
