# Generated by Django 6.0 on 2026-04-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('serial_number', models.IntegerField()),
                ('date', models.DateField()),
                ('fbs', models.CharField(blank=True, max_length=20, null=True)),
                ('pbs', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('net_amount', models.FloatField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
    ]
