# Generated by Django 6.0 on 2026-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_opdbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdbill',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opdbill',
            name='pulse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opdbill',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
