# Generated by Django 6.0 on 2026-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_opdbill_bp_opdbill_pulse_opdbill_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdbill',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbill',
            name='fbs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbill',
            name='pbs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbill',
            name='pulse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opdbill',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
