# Generated by Django 6.0 on 2026-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_opdbill_bp_alter_opdbill_fbs_alter_opdbill_pbs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('aadhaar', models.ImageField(blank=True, null=True, upload_to='aadhaar/')),
                ('license', models.ImageField(blank=True, null=True, upload_to='license/')),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('aadhaar', models.ImageField(blank=True, null=True, upload_to='aadhaar/')),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
    ]
