# Generated by Django 6.0 on 2026-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doctor',
        ),
    ]
