# Generated by Django 6.0 on 2026-04-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_staffmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
