# Generated by Django 6.0 on 2026-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_fitnessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessrecord',
            name='bp_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fitnessrecord',
            name='chol_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='bp_risk',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='chol_risk',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='diabetes_risk',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fitnessrecord',
            name='heart_risk',
            field=models.FloatField(),
        ),
    ]
