# Generated by Django 6.0 on 2026-04-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_category_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, default='strip', max_length=50, null=True),
        ),
    ]
