# Generated by Django 6.0 on 2026-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_medicine_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
