# Generated by Django 6.0 on 2026-04-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_medicine_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mrp',
            field=models.FloatField(default=0),
        ),
    ]
