# Generated by Django 6.0 on 2026-04-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_address_cart_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
